# Generated by Django 5.2.8 on 2025-12-28 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_module', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={},
        ),
        migrations.RemoveField(
            model_name='product',
            name='price',
        ),
        migrations.AddField(
            model_name='product',
            name='is_available',
            field=models.BooleanField(default=True, verbose_name='موجود در انبار'),
        ),
        migrations.AddField(
            model_name='product',
            name='making_charge_percent',
            field=models.FloatField(default=15.0, verbose_name='درصد اجرت ساخت'),
        ),
        migrations.AddField(
            model_name='product',
            name='product_code',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='کد محصول'),
        ),
        migrations.AddField(
            model_name='product',
            name='profit_percent',
            field=models.FloatField(default=7.0, verbose_name='درصد سود فروشگاه'),
        ),
        migrations.AddField(
            model_name='product',
            name='purity',
            field=models.IntegerField(choices=[(18, '۱۸ عیار'), (21, '۲۱ عیار'), (24, '۲۴ عیار')], default=18, verbose_name='عیار طلا'),
        ),
        migrations.AddField(
            model_name='product',
            name='weight_gram',
            field=models.FloatField(default=1.0, verbose_name='وزن (گرم)'),
        ),
        migrations.DeleteModel(
            name='ProductTag',
        ),
    ]
