# Generated by Django 5.2.8 on 2025-12-07 13:51

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GoldPriceHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاریخ')),
                ('gold_18_carat', models.BigIntegerField(blank=True, null=True, verbose_name='طلا 18 عیار')),
                ('gold_20_carat', models.BigIntegerField(blank=True, null=True, verbose_name='طلا 20 عیار')),
                ('gold_21_carat', models.BigIntegerField(blank=True, null=True, verbose_name='طلا 21 عیار')),
                ('gold_18_carat_retail', models.BigIntegerField(blank=True, null=True, verbose_name='خرید متفرقه طلا 18 عیار')),
                ('gold_18_carat_exchange', models.BigIntegerField(blank=True, null=True, verbose_name='تعویض متفرقه طلا 18 عیار')),
                ('gold_nugget', models.BigIntegerField(blank=True, null=True, verbose_name='مظنه نقدی')),
                ('coin_emami', models.BigIntegerField(blank=True, null=True, verbose_name='سکه امامی')),
                ('coin_tamam', models.BigIntegerField(blank=True, null=True, verbose_name='سکه تمام')),
                ('coin_nim', models.BigIntegerField(blank=True, null=True, verbose_name='سکه نیم')),
                ('coin_roob', models.BigIntegerField(blank=True, null=True, verbose_name='سکه ربع')),
                ('coin_gerami', models.BigIntegerField(blank=True, null=True, verbose_name='سکه گرمی')),
                ('currency_usd', models.BigIntegerField(blank=True, null=True, verbose_name='دلار')),
                ('currency_eur', models.BigIntegerField(blank=True, null=True, verbose_name='یورو')),
                ('currency_aed', models.BigIntegerField(blank=True, null=True, verbose_name='درهم')),
                ('source_url', models.URLField(default='https://matisagoldgallery.com/tablo', verbose_name='منبع')),
            ],
            options={
                'verbose_name': 'تاریخچه قیمت طلا',
                'verbose_name_plural': 'تاریخچه قیمت\u200cهای طلا',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='TabloSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auto_update', models.BooleanField(default=True, verbose_name='به\u200cروزرسانی خودکار')),
                ('update_interval_minutes', models.IntegerField(default=5, verbose_name='فاصله به\u200cروزرسانی (دقیقه)')),
                ('last_update', models.DateTimeField(blank=True, null=True, verbose_name='آخرین به\u200cروزرسانی')),
                ('api_enabled', models.BooleanField(default=True, verbose_name='فعال بودن API')),
            ],
            options={
                'verbose_name': 'تنظیمات تابلو',
                'verbose_name_plural': 'تنظیمات تابلو',
            },
        ),
    ]
